spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/cfw
#    dbcp2:
#      default-schema: USSD

  jpa:
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


