spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: qvszootl
    password: QPqI4n6w5LPmmSEkgDtpzH6G6fUrQ3BP
    url: jdbc:postgresql://dumbo.db.elephantsql.com:5432/qvszootl

  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        hibernate.ddl-auto: create


server:
  port: 8095

