spring:
  datasource:
    username: hrm
    password: hrm
    url: jdbc:oracle:thin:@localhost:1521/xe
    dbcp2:
      default-schema: hrm

  jpa:
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect


