#spring:
#  datasource:
#    username: hrm
#    password: hrm
#    url: jdbc:oracle:thin:@localhost:1521/xe
#    dbcp2:
#      default-schema: hrm
#
#  jpa:
#    hibernate.ddl-auto: none
#    generate-ddl: false
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.Oracle12cDialect
#
#

spring:
  datasource:
    username: root
    password:
#    username: frm
#    password: frm@123456
#    url: jdbc:mysql://77.68.25.159:3306/frm
    url: jdbc:mysql://localhost:3306/corm
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect



